# https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html
{% set data = load_setup_py_data() %}

package:
  name: qsum
  version: {{data.get('version')}}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5.0
    - setuptools
  run:
    - python >=3.5
  host:
    - python >=3.5

test:
  files:
    - ../pytest.ini
    - ../mypy.ini
    - ../.pylintrc
  requires:
    - pytest >=4.4.0
    - pytest-pylint
  imports:
    - qsum
    - qsum.core
    - qsum.data
    - qsum.types
    - qsum.core.logic
    - qsum.core.constants
  commands:
    - python -c "import qsum; qsum.test()"

about:
  license_file: LICENSE
  license: {{data.get('license')}}
  home: {{data.get('url')}}
  description: {{data.get('description')}}
  summary: {{data.get('summary')}}