# https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html
{% set data = load_setup_py_data() %}

package:
  name: qsum
  version: {{data.get('version')}}

source:
  path: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=3.5.0
    - setuptools
  run:
    - python >=3.5
  host:
    - python >=3.5

test:
  files:
    - pytest.ini
    - mypy.ini
    - .pylintrc
  requires:
    - pytest >=4.4.0
    - pytest-pylint
  imports:
    - qsum
    - qsum.core
    - qsum.core.logic
    - qsum.core.constants
    - qsum.data
    - qsum.types
    - qsum.util
  commands:
    - python -c "import qsum; qsum.test(use_default_args=False)"

about:
  license_file: LICENSE
  license: {{data.get('license')}}
  home: {{data.get('url')}}
  description: {{data.get('description')}}
  summary: {{data.get('summary')}}