{% set data = load_setup_py_data() %}

package:
  name: qsum
  version: {{data.get('version')}}
source:
  git_url: ../
requirements:
  build:
    - python >=3.5.0
    - setuptools

  run:
    - python >=3.5.0

test:
  requires:
    - pytest >=4.4.0
    - pytest-cov
    - pytest-pylint
    - pytest-xdist
  commands:
    - pytest --cov-report term-missing --cov=qsum -n=auto qsum/

  about:
    license: MIT
    home: {{data.get('url')}}