{% set data = load_setup_py_data() %}

package:
  name: qsum
  version: {{data.get('version')}}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5.0
    - setuptools

  run:
    - python >=3.5

test:
  requires:
    - pytest >=4.4.0
    - pytest-pylint
  imports:
    - qsum
    - qsum.core
    - qsum.data
    - qsum.types
    - qsum.core.logic
    - qsum.core.constants
  commands:
    - pytest

about:
  license: MIT
  home: {{data.get('url')}}