name: Python Package using Conda

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "3.12" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: qsum_dev
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
        show-channel-urls: true
        use-only-tar-bz2: true
    - name: Conda Info
      shell: bash -el {0}
      run: |
        conda info
        conda list
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        pytest
